[package]
name = "filetime-fix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filetime = "0.2.17"
rexif = "0.7.3"
chrono = "0.4"
log = "0.4"
env_logger = "0.9"